### ISSUE TITLE
Duplicated code ¿?

### ISSUE THREAD

**Issue by gaceladri** [VITA-Group/BERT-Tickets#1]
Hello,

Thanks for this repo. I am trying to extract the GraSP code from:
https://github.com/VITA-Group/BERT-Tickets/blob/master/pretrain_grasp.py

But in https://github.com/VITA-Group/BERT-Tickets/blob/master/pretrain_grasp.py#L431 there is no import or definition of this function inside the .py. I mean, I have not tried to run the file but if it is not declared or imported from anywhere I imagine that it is not going to work.

[Here](https://github.com/VITA-Group/BERT-Tickets/blob/c55e3d9ed21c4a66a58de0f3d1a0d64ca7f73653/pretrain_grasp.py#L52) you have commented the imports. Should I uncomment this line to import the _pruning_model_custom_, _see_weight_rate_, and _pruning_model_?

Is for this reason that I don't like to do absolute imports with * because you use to loose the trace. :(

Big anticipated thanks.
Best regards

**Comment by Tianlong-Chen** [comment]
Refer to the #2
